# Generated by Django 5.2.3 on 2025-07-07 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Location'), ('ONLINE', 'Online Event')], default='PHYSICAL', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='online_url',
            field=models.URLField(blank=True, help_text='URL for online event (required for online events)', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Physical address or venue name', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
