# Generated by Django 5.2.3 on 2025-07-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hapu_options_hapu_archived_at_hapu_archived_by_and_more'),
        ('events', '0002_event_location_type_event_online_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hapu',
            field=models.ForeignKey(blank=True, help_text='Specific hapu for hapu-specific events', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hapu'),
        ),
        migrations.AddField(
            model_name='event',
            name='iwi',
            field=models.ForeignKey(blank=True, help_text='Specific iwi for iwi-specific events', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.iwi'),
        ),
    ]
