# Generated by Django 5.2.3 on 2025-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=32),
        ),
    ]
