# Generated by Django 5.2.3 on 2025-07-01 15:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='citizenship_document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.citizenship_document_upload_to),
        ),
    ]
