# Generated by Django 5.2.3 on 2025-07-01 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_citizenship_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
