# Generated by Django 5.2.3 on 2025-07-01 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HapuLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hapu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.hapu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hapu_leaderships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hapu', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IwiLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.iwi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iwi_leaderships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('iwi', 'user')},
            },
        ),
    ]
