# Generated by Django 5.2.3 on 2025-07-05 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hapuleader_iwileader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iwi',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='iwi',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iwi',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_iwis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iwi',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
