# Generated by Django 5.2.3 on 2025-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_proposalcomment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
